export const groceries = [
  {
    quantity: 1,
    id: 1,
    name: "Frutilla",
    unitPrice: 50.3,
  },
  { quantity: 1, id: 2, name: "Uva", unitPrice: 23.0 },
  { quantity: 1, id: 3, name: "Naranja", unitPrice: 76.0 },
  { quantity: 1, id: 4, name: "Banana", unitPrice: 55.9 },
  { quantity: 1, id: 5, name: "Manzana", unitPrice: 31.0 },
  { quantity: 1, id: 6, name: "Zanahoria", unitPrice: 17.6 },
  { quantity: 1, id: 7, name: "Puerro", unitPrice: 30.0 },
  { quantity: 1, id: 8, name: "Champiñon", unitPrice: 80.0 },
  { quantity: 1, id: 9, name: "Pan", unitPrice: 22.5 },
  { quantity: 1, id: 10, name: "Huevo", unitPrice: 29.0 },
  { quantity: 1, id: 11, name: "Queso", unitPrice: 130.0 },
  { quantity: 1, id: 12, name: "Manteca", unitPrice: 90.0 },
  { quantity: 1, id: 13, name: "Pollo", unitPrice: 115.0 },
  { quantity: 1, id: 14, name: "Milanesa", unitPrice: 97.0 },
  { quantity: 1, id: 15, name: "Helado", unitPrice: 88.0 },
  { quantity: 1, id: 16, name: "Pescado", unitPrice: 150.0 },
  { quantity: 1, id: 17, name: "Arroz", unitPrice: 36.0 },
  { quantity: 1, id: 18, name: "Fideos", unitPrice: 56.0 },
  { quantity: 1, id: 19, name: "Bizcocho", unitPrice: 72.0 },
  { quantity: 1, id: 20, name: "Papel Higiénico", unitPrice: 45.0 },
  { quantity: 1, id: 21, name: "Alcohol en Gel", unitPrice: 83.0 },
];
